### ISSUE TITLE
Fails to use APM policy with IDPs that use SSL certificates

### ISSUE THREAD

**Issue by lm-sig** [F5Networks/f5-appsvcs-extension#141]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.13.1-1.noarch.rpm
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.3
  Build       0.0.6
  Edition     Final
  Date        Fri Aug  2 20:39:15 PDT 2019
```

##### SUMMARY

In attempting to create a VIP with one of our existing APM policies the deployment fails.

The policy uses SAML and ADFS servers.

##### STEPS TO REPRODUCE

```
    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.13.0",
            "id": "test-declaration-0",
            "label": "Test Declaration 0",
            "remark": "Test Declaration for My Apps",
            "Partition": {
                "class": "Tenant",
                "MyApp1": {
                    "class": "Application",
                    "template": "generic",
                    "MyApp1_VIP": {
                        "class": "Service_HTTPS",
                        ...
                        "policyIAM": {
                            "bigip": "/Partition/SAML_APL_TEST"
                        },
                        ...
                }
            }
        }
    }
```

##### EXPECTED RESULTS

```
Successful deployment with a VIP that has my APM policy.
```

##### ACTUAL RESULTS

```
01070265:3: The Certificate File (/Partition/SAML_APL_TEST-sub.external-domain.com.crt) cannot be deleted because it is in use by a IDP Connector (/Partition/SAML_APL_TEST-sub.domain.com).
```

**Comment by lm-sig** [comment]
The problem seems to be the fact I loaded the policy into the same partition as where AS3 deploys.

If I load the policy in Common I can attach the policy without error. It's a workaround for now, but it would be nice to have the policy in the same partition.

**Comment by Kupoman** [comment]
AS3 assumes full ownership of any partition (with Common being a special case) that it is configuring. It is not recommended to do any configuration of an AS3 tenant outside of AS3. In order to have the policy in the AS3 partition, it should be created by AS3. Unfortunately, AS3 does not currently support creation of APM policies.

**Comment by dstokesf5** [comment]
AS3 assumes full ownership of any partition (with Common being a special case) that it is configuring. It is not recommended to do any configuration of an AS3 tenant outside of AS3. In order to have the policy in the AS3 partition, it should be created by AS3. Unfortunately, AS3 does not currently support creation of APM policies.
