### ISSUE TITLE
Unable to add BIG-IQ managed WAF Policy in AS3

### ISSUE THREAD

**Issue by pythongelenk** [F5Networks/f5-appsvcs-extension#157]
#### Do you already have an issue opened with F5 support?
no

##### ISSUE TYPE

 - Feature Idea

##### AS3 BUILD/ VERSION

```
3.12.1-2
```

##### BIGIP VERSION

```
Main Package
  Product     BIG-IQ
  Version     7.0.0
  Build       0.0.1854
  Edition     Final
```

##### SUMMARY

```
We are using F5 BIG-IQ for WAF Policy Management at our site.
We would like to automate our app deployment using AS3. Unfortunately we are unable to pass BIG-IQ Managed Objects into AS3 Declarations.
```

**Comment by dstokesf5** [comment]
In order to use BIG-IQ to manage WAF policies and use them with AS3, you need to publish the WAF policies to the BIG-IP from BIG-IQ. Then you can use a "bigip" style reference in your AS3 declaration to reference the WAF policy.

In order for AS3 to better automate this process, we would need BIG-IQ to have an endpoint that AS3 can download the WAF policies from.
