### ISSUE TITLE
Dynamic EP discovery fails for Mapping where multiple  BigIP Partitions/Apps are mapped to same APIC EPG

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#187]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE
 - Bug Report
##### AS3 BUILD/ VERSION
AS3 :  v3.15.0-2
##### BIGIP VERSION
v13.1, 14.1
##### SUMMARY
- Configured dynamic EP discovery for 3 BigIP Partitions ( Part1,Part2,Part3 ) and 3 Apps ( App1,App2,App3 respectively ) - mapped to same EPG under APIC one Tenant.
- Attached Endpoint to this APIC EPG which triggered node and pool-member add operation.
- However, the node was added only under first BigIP partition/app and not under remaining 2 partitions.

##### EXPECTED RESULTS
Either The endpoints should have been discovered and should have been added to respective pools or if the config is unsupported, AS3 should respond with error.

##### ACTUAL RESULTS
Following details were observed for id field under each partition/app service discovery :
Partition 1 :  "id": "/Part1/192.168.11.100"
Partition 2 : "id": "/Part2/Part1/192.168.11.100"
Partition 3 : "id": "/Part3/Part1/192.168.11.100"

Detailed output from Service discovery endpoint for below Partitions :

Part1/App1

// https://10.107.0.22/mgmt/shared/service-discovery/task/~Part1~App1~svc_pool

{
"code": 200,
"result": {
"id": "~Part1~App1~svc_pool",
"updateInterval": 0,
"provider": "event",
"providerOptions": {
"type": "event",
"nodeList": [
{
"ip": "192.168.11.100",
"id": "/Part1/192.168.11.100"
}
]
},
"resources": [
{
"type": "pool",
"path": "/Part1/App1/svc_pool",
"options": {
"servicePort": 1114,
"connectionLimit": 0,
"rateLimit": "disabled",
"dynamicRatio": 1,
"ratio": 1,
"priorityGroup": 0,
"monitor": "default"
},
"requiresNodes": true
}
],
"kind": "shared:service-discovery:taskstate",
"lastRun": "2019-09-16T12:09:47.159Z",
"nodePrefix": "/Part1/"
}
}

Part2/App2 :

// https://10.107.0.22/mgmt/shared/service-discovery/task/~Part2~App2~svc_pool

{
"code": 200,
"result": {
"id": "~Part2~App2~svc_pool",
"updateInterval": 0,
"provider": "event",
"providerOptions": {
"type": "event",
"nodeList": [
{
"ip": "192.168.11.100",
"id": "/Part2/Part1/192.168.11.100"
}
]
},
"resources": [
{
"type": "pool",
"path": "/Part2/App2/svc_pool",
"options": {
"servicePort": 2223,
"connectionLimit": 0,
"rateLimit": "disabled",
"dynamicRatio": 1,
"ratio": 1,
"priorityGroup": 0,
"monitor": "default"
},
"requiresNodes": true
}
],
"kind": "shared:service-discovery:taskstate",
"lastRun": "2019-09-16T12:09:50.952Z",
"nodePrefix": "/Part2/"
}
}

Part3/App3 :

// https://10.107.0.22/mgmt/shared/service-discovery/task/~Part3~App3~svc_pool

{
"code": 200,
"result": {
"id": "~Part3~App3~svc_pool",
"updateInterval": 0,
"provider": "event",
"providerOptions": {
"type": "event",
"nodeList": [
{
"ip": "192.168.11.100",
"id": "/Part3/Part1/192.168.11.100"
}
]
},
"resources": [
{
"type": "pool",
"path": "/Part3/App3/svc_pool",
"options": {
"servicePort": 3334,
"connectionLimit": 0,
"rateLimit": "disabled",
"dynamicRatio": 1,
"ratio": 1,
"priorityGroup": 0,
"monitor": "default"
},
"requiresNodes": true
}
],
"kind": "shared:service-discovery:taskstate",
"lastRun": "2019-09-16T12:09:52.953Z",
"nodePrefix": "/Part3/"
}
}

**Comment by dstokesf5** [comment]
Can you please describe the problem and the steps to reproduce the problem using only AS3 without APIC or EPG?

**Comment by manukanade** [comment]
Hi, Adding the steps just with AS3 posts done to the BIG-IP

**Step1:** The BIG-IP has 2 partitions. Each partition has an application with service discovery enabled:
**GET https://BIGIP_IP/mgmt/shared/service-discovery/task/~partition1~app1~web_pool:**

{"code":200,"result":{"id":"~partition1~app1~web_pool","updateInterval":0,"provider":"event","providerOptions":{"type":"event","nodeList":[]},"resources":[{"type":"pool","path":"/partition1/app1/web_pool","options":{"servicePort":9090,"connectionLimit":0,"rateLimit":"disabled","dynamicRatio":1,"ratio":1,"priorityGroup":0,"monitor":"default"},"requiresNodes":true}],"kind":"shared:service-discovery:taskstate","lastRun":"2019-11-15T10:57:24.533Z","nodePrefix":"/partition1/"}}


**GET https://BIGIP_IP/mgmt/shared/service-discovery/task/~partition2~app2~web_pool**
{"code":200,"result":{"id":"~partition2~app2~web_pool","updateInterval":0,"provider":"event","providerOptions":{"type":"event","nodeList":[]},"resources":[{"type":"pool","path":"/partition2/app2/web_pool","options":{"servicePort":7070,"connectionLimit":0,"rateLimit":"disabled","dynamicRatio":1,"ratio":1,"priorityGroup":0,"monitor":"default"},"requiresNodes":true}],"kind":"shared:service-discovery:taskstate","lastRun":"2019-11-15T10:58:24.095Z","nodePrefix":"/partition2/"}}


**Step 2**: POST node list to 1st partition **https://BIGIP_IP/mgmt/shared/service-discovery/task/~partition1~app1~web_pool/nodes.** Posted this list [{"id": "192.168.10.10", "ip": "192.168.10.10"}, {"id": "192.168.10.11", "ip": "192.168.10.11"}]. Operation was successful and nodes got created on BIG-IP. 

GET on both the discovery endpoints for partition1's app and partition 2's app are as below at this point:
GET on both pools:

{"code":200,"result":{"id":"~partition1~app1~web_pool","updateInterval":0,"provider":"event","providerOptions":{"type":"event","nodeList":[{"id":"/partition1/192.168.10.10","ip":"192.168.10.10"},{"id":"/partition1/192.168.10.11","ip":"192.168.10.11"}]},"resources":[{"type":"pool","path":"/partition1/app1/web_pool","options":{"servicePort":9090,"connectionLimit":0,"rateLimit":"disabled","dynamicRatio":1,"ratio":1,"priorityGroup":0,"monitor":"default"},"requiresNodes":true}],"kind":"shared:service-discovery:taskstate","lastRun":"2019-11-15T11:02:40.381Z","nodePrefix":"/partition1/"}}


{"code":200,"result":{"id":"~partition2~app2~web_pool","updateInterval":0,"provider":"event","providerOptions":{"type":"event","nodeList":[]},"resources":[{"type":"pool","path":"/partition2/app2/web_pool","options":{"servicePort":7070,"connectionLimit":0,"rateLimit":"disabled","dynamicRatio":1,"ratio":1,"priorityGroup":0,"monitor":"default"},"requiresNodes":true}],"kind":"shared:service-discovery:taskstate","lastRun":"2019-11-15T10:58:24.095Z","nodePrefix":"/partition2/"}}

**Step 3**: Post the same endpoint list to 2nd partition's service discovery endpoint **https://BIGIP_IP/mgmt/shared/service-discovery/task/~partition2~app2~web_pool/nodes**. Posted node list 
[{"id": "192.168.10.10", "ip": "192.168.10.10"}, {"id": "192.168.10.11", "ip": "192.168.10.11"}]

**Issue Reproduced**: 
1. At this point AS3 responds with 200 OK and does not give any error atall. But the endpoints also don't get created in partition2 maybe since those same nodes are already present in the other partition. If this is not a supported config, then the expectation would be that  AS3 errors out on posting same endpoint IPs to 2nd partition OR else create all nodes in Common partition and allow them to be part of multiple pools belonging to different partitions. 

2. Other issue is the ID of the endpoints gets messed up. GET on 2nd app from 2nd partition: https://BIGIP_IP/mgmt/shared/service-discovery/task/~partition2~app2~web_pool returns 

{"code":200,"result":{"id":"~partition2~app2~web_pool","updateInterval":0,"provider":"event","providerOptions":{"type":"event","nodeList":[{"id":"/partition2/192.168.10.10","ip":"192.168.10.10"},{"id":"/partition2//partition1/192.168.10.11","ip":"192.168.10.11"}]},"resources":[{"type":"pool","path":"/partition2/app2/web_pool","options":{"servicePort":7070,"connectionLimit":0,"rateLimit":"disabled","dynamicRatio":1,"ratio":1,"priorityGroup":0,"monitor":"default"},"requiresNodes":true}],"kind":"shared:service-discovery:taskstate","lastRun":"2019-11-15T11:04:26.900Z","nodePrefix":"/partition2/"}}

As can be seen the id is /partition2//partition1/192.168.10.11 which does not seem like the right

**Comment by dstokesf5** [comment]
If you want to use the same nodes between multiple applications, you should set `shareNodes` to `true` in the declaration to put the nodes into /Common:
```json
{
    "schemaVersion": "3.0.0",
    "class": "ADC",
    "Tenant": {
        "Application": {
            "web_pool": {
                "class": "Pool",
                "members": [{
                        "addressDiscovery": "event",
                        "shareNodes": true,
                        "servicePort": 9090
                    }
                ],
                "monitors": ["http"]
            },
            "class": "Application",
            "template": "http",
            "serviceMain": {
                "class": "Service_HTTP",
                "pool": "web_pool",
                "virtualAddresses": ["10.10.10.10"]
            }
        },
        "class": "Tenant"
    }
}
```

**Comment by manukanade** [comment]
Thanks for the response @dstokesf5 . We will try the shareNodes option. But is somebody mis-configures - there is no error response from AS3 - is it possible for AS3 service discovery to error out when shareNodes is not true and somebody tries to use the same IP address to a different partition. 

Also can this shareNodes option be documented on link https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html? Or where else would this be documented. Thanks.

**Comment by dstokesf5** [comment]
I think the shareNodes option is only currently documented here: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#pool-member

It looks like the service discovery worker that AS3 relies on is trying to make things work, which is why it is not returning an error. Unfortunately, it got things wrong.

**Comment by kedargslab** [comment]
@dstokesf5  So, based on above 2 comments in the thread, AS3 should respond with error if user tries above type of config with multiple partitions.

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by kedargslab** [comment]
Verified the ""shareNodes": true " option worked for above issue. We were able to create node in common partition and add it as a member under multiple partitions using service discovery endpoint config .
