### ISSUE TITLE
Expand available settings for Bot Defense

### ISSUE THREAD

**Issue by michal-malec** [F5Networks/f5-appsvcs-extension#218]
### Is your feature request related to a problem? Please describe.
After studying current AS3 documentation I haven't found possibility to setup most of new Bot Defense parameters.

### Describe the solution you'd like
I would like to be able to setup all Bot Defense settings via AS3. Especially settings like:
1. API Access for Browsers and Mobile Applications
2. Mitigation settings - type and additional parameters like number of transactions per second for Rate Limit mitigation
3. Signatures Enforcement

### Describe alternatives you've considered
I quickly reviewed iControl Rest, TMSH and Python SDK documentations and it seems that currently it is not possible to alter these settings automatically. Please let me know if I am wrong.

### Additional context
In order to use F5 WAF in cloud I have to setup everything automatically.

**Comment by michal-malec** [comment]
I found a way to create a Bot Profile using iControl REST, however it would be great to have this feature in AS3. Currently I have to use two tools to setup BIG-IP.

**Comment by dstokesf5** [comment]
This is already in our internal product backlog as AUTOTOOL-46.

**Comment by megamattzilla** [comment]
I have customers running into this now as well using TMOS 15.1.2.1 and AS3 3.26.0. 

We can create virtual servers, WAF policies, DoS profiles in AS3 but we cannot create the unified (TMOS 14.1.x+) bot defense profiles which are required by the customer. 

We would like to see the ability to create bot defense profiles added to AS3, so that we don't have to create them manually outside AS3 and reference them using the _bigip_ pointer.

**Comment by delgadillo22** [comment]
Policy editing & lifecycle management are beyond the scope of AS3.
Recommend using BIG-IQ as appropriate.
Closing this issue.
