### ISSUE TITLE
AS3 Minor versions are not supported 

### ISSUE THREAD

**Issue by vklohiya** [F5Networks/f5-appsvcs-extension#227]
### Environment
 * Application Services Version: 3.13.1
 * BIG-IP Version: 14.1

### Summary
AS3 Minor versions are not supported in AS3 json
### Steps To Reproduce
1. Submit the following declaration:
```json
{
   "class": "AS3",
   "action": "deploy",
   "persist": true,
   "declaration": {
      "class": "ADC",
      "schemaVersion": "3.13.1",
      "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
      "label": "Sample 1",
      "remark": "Simple HTTP application with RR pool",
      "Sample_01": {
         "class": "Tenant",
         "A1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
               "class": "Service_HTTP",
               "virtualAddresses": [
                  "10.0.1.10"
               ],
               "pool": "web_pool"
            },
            "web_pool": {
               "class": "Pool",
               "monitors": [
                  "http"
               ],
               "members": [{
                  "servicePort": 80,
                  "serverAddresses": [
                     "192.0.1.10",
                     "192.0.1.11"
                  ]
               }]
            }
         }
      }
   }
}
```

2. Observe the following error response:
```json
{
  "code": 422,
  "errors": [
    "/schemaVersion: should be equal to one of the allowed values [\"3.0.0\",\"3.1.0\",\"3.2.0\",\"3.3.0\",\"3.4.0\",\"3.5.0\",\"3.6.0\",\"3.7.0\",\"3.8.0\",\"3.9.0\",\"3.10.0\",\"3.11.0\",\"3.12.0\",\"3.13.0\",\"3.14.0\",\"3.15.0\"]"
  ],
  "declarationFullId": "",
  "message": "declaration is invalid"
}
```

### Expected Behavior
It should accept minor versions as well

### Actual Behavior
AS3 responded with 422 error.

**Comment by dstokesf5** [comment]
We discovered that trying to manage the minor versions in the schema was too much of a burden across branches. AS3 follows [semantic versioning](https://semver.org/). This means that there should be no change in API/schema between minor versions. Because of this, the schema effectively just specifies the major and minor version you wish to target. The patch version being included in the declaration is mostly a leftover from AS3's early days that is preserved for the sake of compatibility.
