### ISSUE TITLE
No configuration option to enable a node monitor?

### ISSUE THREAD

**Issue by manhac** [F5Networks/f5-appsvcs-extension#333]
### Environment
 * Application Services Version: 3.21
 * BIG-IP Version: 15.1.0.4

### Feature
For pool members created with AS3, I would like to see an ICMP status in the nodes section of the TMUI, as this can be helpful for debugging or to get a quick overview of the scope of a problem.
However, I cannot seem to find the suitable options in the AS3 schema reference to configure either per node monitors or a default monitor for all nodes in a partition.

Looking at https://github.com/F5Networks/f5-appsvcs-extension/issues/112 I wonder if this is even possible. It would be great, if this feature could be added!

**Comment by DaanOlbrechts** [comment]
Commenting to indicate additional interest for this functionality. Before AS3 we were using node-level SNMP DCA monitors and Dynamic Ratio load balancing, we'd now like to implement an equivalent configuration using AS3 but currently this doesn't seem possible.

**Comment by walterk82** [comment]
I just ran into this issue, as my device default node monitor is ICMP with a long polling interval.  This is required so that we can true-up the environment as the server topology changes and cleanup is required of BIG-IP configuration.  The lack of this AS3 feature is problematic for pool members which are internet sites or fqdn's to remote vendors as ICMP is frequently blocked across the internet.  I have found that you can manually change the node to a monitor of "None", and that AS3 never checks this value upon re-deployment of the tenant.  However, this is not a reliable process.

**Comment by j-zehnder** [comment]
Is it possible to get an update on the status of this issue?

**Comment by walterk82** [comment]
@dstokesf5 Can you triage this request?  Thanks.

**Comment by sunitharonan** [comment]
Thank you for reaching out. In order to prioritize and understand the issue better, please reach out to us at automation_toolchain_pm@f5.com

**Comment by sunitharonan** [comment]
AUTOTOOL-4307 has been created and added to our internal product backlog
