### ISSUE TITLE
Unable to bind same egress and ingress TCP profile

### ISSUE THREAD

**Issue by oakh1** [F5Networks/f5-appsvcs-extension#335]
### Environment
 * Application Services Version: 3.21.0
 * BIG-IP Version: 15.1

### Summary
When I try to deploy a declaration with a HTTPS service that has the same ingress and egress TCP profile I get the following 422 error back:
01070734:3: Configuration error: Less than the required minimum number of profiles
Exactly 1 of (UDP Profile (clientside), TCP Profile (clientside), SCTP Profile (clientside))

If I instead use 2 different TCP profiles, it works.

**Not working**:
      "profileTCP": {
        "ingress": "lan",
        "egress": "lan"
      },

**Works**:
      "profileTCP": {
        "ingress": "mobile",
        "egress": "lan"
      },

See this issue: https://github.com/F5Networks/f5-appsvcs-templates/issues/10
Ps, I'm using pure AS3, not FAST.

**Comment by dstokesf5** [comment]
Specifying the same profile for ingress and egress results in a tmsh command similar to `create ltm virtual example profiles replace-all-with { f5-tcp-lan { context clientside } f5-tcp-lan { context serverside } }`, which tmsh does not like. To set a profile to both contexts, a command similar to `create ltm virtual example profiles replace-all-with { f5-tcp-lan { context all } }` is needed, which you will get if you set the AS3 profileTcp property to "lan" instead of an object.

Does setting the profileTcp property to a string work for your use case, or is there a reason you need to use the object instead?

**Comment by oakh1** [comment]
Thanks for the information.

Well, it works to use a string or an object with different profiles. I understand your example with the tmsh command but it would be preferable if it could be possible to do it this way. Makes our templating/automation a bit cleaner if we could keep a "standardized" design using objects (which then would work to set both the same profiles or different as we have to do now).

Either way, it's not the most important thing but should be doable. But it's to know there's a (two) workarounds.

**Comment by dstokesf5** [comment]
Thank you for clarifying your use case, and I agree getting this issue resolved would be helpful for it. I have added this bug to our internal product backlog as AUTOTOOL-1883.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
