### ISSUE TITLE
Private Key is clear text

### ISSUE THREAD

**Issue by danpacheco1** [F5Networks/f5-appsvcs-extension#351]
### Is your feature request related to a problem? Please describe.
With declarations that contain a cert, i.e. "class": "Certificate", the private key is in clear text. This poses a security risk depending on where depending on where our declarations are stored (git repo) and who has access.

### Describe the solution you'd like
The option to obfuscate and/or encrypt the private key similar to what is done with passwords/passphrases in HTTP monitors.

### Describe alternatives you've considered
Not including the private key text in the declaration. Instead referencing it from the shared partition, example:
privateKey": {
                       "bigip": "/Common/default.key"
                   }
However, this requires manual intervention and does not align with our automation principles.

**Comment by markchart** [comment]
The solution for you (this is normal practice, not some hack):  encrypt the private key under a passphrase, put the encrypted private key into the `privateKey` attribute of the `Certificate` object and put the passphrase into the `passphrase` attribute of the same `Certificate` object.  The `passphrase` attribute value is a `Secret` value which you may supply as plaintext (encoded in base-64) or as a SecureVault cryptogram (encrypted with the BIG-IP cluster's master key).  AS3 automatically converts plaintext secrets to SecureVault cryptograms so passphrases are always encrypted in the BIG-IP configuration and when you GET a copy of a declaration from AS3 all the secrets in it are SV cryptograms.  You can GET a copy of your declaration from AS3 to obtain the SecureVault cryptograms for passphrases and such and store those in your declaration archive instead of plaintexts.

To encrypt your private key you can use an `openssl` command similar to this example:  `openssl rsa -aes256 -in example.net-plaintext.key -out example.net-encrypted.key`
