### ISSUE TITLE
AS3 validation offline

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-appsvcs-extension#362]
### Is your feature request related to a problem? Please describe.
The kubernetes cluster is in a dark environment without Internet. Would like to validate as3 offline if possible. 

### Describe the solution you'd like

Something like being able to validate AS3 declarations directly within VSCode or Atom. 

### Describe alternatives you've considered

Below is a similar request. 
https://github.com/F5Networks/f5-appsvcs-extension/issues/38

### Additional context

Currently configuring AS3 configmaps by hand and often run into syntax issues when deploying in kubernetes. Must sift through CIS logs to figure out root cause.

**Comment by jmcalalang** [comment]
The way that I have navigated around this problem (it might not fit you), with something that can be consumed in a pipeline is to use an external JSON validator. Most validators will need a format defined for some of our objects (or it will only be structural) but below is an example of a flow:
 

1. - Survey/build with parameters for use in AS3 template (vips, tenant, pool members), or handed down from upstream orchestration
2. - The job combines parameters with the template (like jinja)
3. - New Service Template is placed in a location (like source control or local storage)
4. - Have a local copy of the AS3 Schema, or download the latest copy first
5. - Execute an AJV cli command against the AS3 Schema and the New Service Template(s)
6. - Expect response to be “valid”
7. - Progress to next step

 
Any JSON validator can be used since the whole schema is public, so if you already use one for other solutions that could be reused.
 
For example I use AJV, I like it since I can validate lots of AS3 Declarations at once.
 
AJV: https://ajv.js.org/

- Specifically all I use with this is the CLI
- CLI installation: https://github.com/jessedc/ajv-cli

 
Example:
 
```
ajv validate -s /Users/calalang/Downloads/f5-appsvcs-extension-master/schema/latest/as3-schema-3.18.0-4.json -d "/Users/calalang/Desktop/as3_declaration_0*.json" --unknown-formats=ignore
/Users/calalang/Desktop/as3_declaration_01.json valid
/Users/calalang/Desktop/as3_declaration_02.json valid
 
```
 
There are many others, its crude, but here is something similar against the https://www.jsonschemavalidator.net/ API just to show another:
 
![Unknown](https://user-images.githubusercontent.com/20847865/95878972-ac927900-0d2a-11eb-8a12-a42dc0ba3569.png)

**Comment by dstokesf5** [comment]
Instructions for validating AS3 declarations with VS Code, can be found here: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/validate.html

If you want to do it offline, you will need to download the schema file ahead of time, and then point the `$schema` property to that local file.
