### ISSUE TITLE
POST generates very large patch files

### ISSUE THREAD

**Issue by jeremy-py** [F5Networks/f5-appsvcs-extension#413]
### Environment
 * Application Services Version: 3.24
 * BIG-IP Version: 13.X & 15.X

### Summary
On each POST, AS3 generates a "patch" file located inside `/config/.diffVersions/config/bigip.conf/` folder.  
Those files are generated by `tmsh save sys config` (ran by AS3 as well?)

On non-orchestrated devices, all patch files are very low size, around 1KB.
Through AS3, on orchestrated devices, patch files are around 1MB, up to 3MB. Content are very verbose and seems to be encrypted (and it is not on non-orchestrated devices).

Consequence, we may have issue of partition saturation on different places (/config, /var with ucs...)

### Expected Behavior
Decrease the size of patch files or equivalent.

### Actual Behavior
We have a high usage of AS3 and that behavior can break orchestration, deployment, due to partition saturation.  
It could also have others bad side effects (on asm, ...).

**Comment by dstokesf5** [comment]
Unfortunately, AS3 has little to no control over `/config/.diffVersions`. AS3 does call `tmsh save sys config` to persist changes to disk, but I do not see any options in the help page for `sys config` that might affect `/config/.diffVersions`.

You can disable this persistence to disk by setting the persist property of the AS3 class to false: https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/composing-a-declaration.html

**Comment by dstokesf5** [comment]
I have reached out to some fellow F5ers to see if there is any way that AS3 can avoid generating those diffs when persisting the configuration. I came across a feature request for BIG-IP to add a DB variable to disable the generation of those diff files. The issue ID is 773493. If you need this functionality, I recommend creating a ticket with F5 support to put more pressure on that ID.

Since this is a problem with BIG-IP that AS3 can do little to nothing about, I am closing this issue.
