### ISSUE TITLE
SNAT_Pool with Self IP

### ISSUE THREAD

**Issue by stanislaspiron** [F5Networks/f5-appsvcs-extension#415]
### Is your feature request related to a problem? Please describe.
When running Cloud-init, the we can't provide self-ip information to AS3 when self-ip is discovered with tmos_dhcpv4_tmm module. 
this module will assign self-ip name like : selfip_1_<interface ID>

So if we want to create a default SNAT POOL with self-ip address, we must first do an iControl or DO request to get this IP address, then POST modified AS3 with SNAT_Pool class.

### Describe the solution you'd like
Support bigip reference to local objects in SNAT_Pool Class like:

```
"SNAT_POOL": {
    "class": "SNAT_Pool",
    "snatAddresses": [
        { 
            "type": "selfip",
            "bigip": "/Common/selfip_1_1"
        }
    ]
}
```

**Comment by dstokesf5** [comment]
Thank you for your feedback. Unfortunately, we have decided that supporting this kind of functionality to a satisfactory level is outside of the scope of AS3. Because AS3 only does work when a declaration is submitted, this kind of functionality could provide a poor user experience if the self ip changes.
