### ISSUE TITLE
AS3 Open Source or Reconciliation Loop documented?

### ISSUE THREAD

**Issue by rayterrill** [F5Networks/f5-appsvcs-extension#468]
### Is your feature request related to a problem? Please describe.
Not sure this is the right spot for this, but giving it a shot. Is AS3 going to be open sourced, or is the source available? If not - is there documentation somewhere that describes how the reconciliation loop functionality works - specifically how AS3 decides whether/not something needs to be updated?

The majority of our App/LTM configuration is in AS3 via Ansible, and working through APM configuration over REST which is downright painful. Leveraging a higher-order tool like AS3 that sits above the REST layer would be ideal.

### Describe the solution you'd like
Open source/visibility into how AS3 works, so it or potentially the underlying idea could potentially be leveraged for other solutions (APM, etc)

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by dstokesf5** [comment]
Well this is awkward. I thought we were publishing an archive of the source code with each GitHub release. While we do create that archive as part of our build process, it turns out we are not publishing it due to a sensitive file. This file is no longer needed in versions 3.27.0 and beyond. The sensitive file is being removed so we can include the source code archive on future releases.

At some point in the future, we would like to push the internal AS3 repository to GitHub like we do for Declarative Onboarding and Telemetry Streaming. However, it is unclear at this time when we will be able to do that.

**Comment by rayterrill** [comment]
@dstokesf5 this made me laugh - appreciate the response. :) Really dig using AS3 and would love to see it extended if possible to cover other parts of F5 (even if we have to look at doing that ourselves).

**Comment by walterk82** [comment]
It would really be beneficial to all consumers for F5 to accept pull requests from contributors for all automation tool chain extensions.  It seems that there are more RFEs filed than there is time for F5 development to fulfill.  This can lead to poor adoption (in my experience) as customers are waiting for TMOS/AS3 feature parity.  It could also be said that Engineering needs to consider the ramifications of making schema changes to the product stack before having the support in the toolchains to configure the features.

**Comment by dstokesf5** [comment]
In theory, we do accept pull requests for Declarative Onboarding and Telemetry Streaming, with the intent of also making it possible to submit pull requests for AS3. F5 requires that all contributors sign a contributor license agreement: https://github.com/F5Networks/f5-appsvcs-extension#f5-networks-contributor-license-agreement.

In practice, the process of accepting pull requests is not well tested because we have seen a very low volume of pull requests for these three projects. If we saw an increase in pull request volume, we would likely need to make some improvements to the process.
