### ISSUE TITLE
Regex for pool names does not contain dash character

### ISSUE THREAD

**Issue by krambone95** [F5Networks/f5-appsvcs-extension#49]
##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION
```
3.7.0
```
##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.3
  Build       0.0.1
  Edition     Point Release 3
  Date        Wed Nov 28 18:50:45 PST 2018
```

##### SUMMARY
```
Regex for pool name does not include dash character, which is a valid character.
```

##### STEPS TO REPRODUCE

```

```

##### EXPECTED RESULTS
Dash "-" is a valid character for F5 pool name, but is not included in regex.

##### ACTUAL RESULTS

```
{'code': 422,
 'declarationFullId': '',
 'errors': ['/POD31/lvsp31_pools: propertyName "BLAH-BLA_443" should match '
            'pattern "^[A-Za-z][0-9A-Za-z_]{0,47}$"'],
 'message': 'declaration is invalid'}
```

**Comment by kaustriaf5** [comment]
Hi @krambone95,

This exclusion of hyphen is deliberate / by design and is not a bug. This pattern check is applied to other big-ip components and not just the pool name. 

We have opened internal issue 805 to improve our documentation regarding this. 
We do have a bit of explanation, currently available on [clouddocs: as3-declarations-and-big-ip-configuration-component-names](
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/declaration-purpose-function.html?highlight=hyphen#as3-declarations-and-big-ip-configuration-component-names)

Thanks,
Kat

**Comment by kaustriaf5** [comment]
This has been added to our cloud docs page. See https://cloudsolutions.pages.gitswarm.f5net.com/f5-appsvcs/userguide/tips-warnings.html?highlight=dash/hyphen%20(-)#notes-and-tips
