### ISSUE TITLE
Q: How to delete all AS3 content for /Common/Shared?

### ISSUE THREAD

**Issue by ghalevy** [F5Networks/f5-appsvcs-extension#602]
Following reference for `DELETE` below:

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/as3-api.html#delete-ref

Tried: 

- sending `DELETE` HTTP method to AS3 endpoint `/mgmt/shared/appsvcs/declare`, fails `422` on dependency items
- sending blank declaration for `Common` tenant, fails `422` on any dependency items.
- sending `"action": "remove"`, fails `422` on dependency items.

Would like to be able to simply delete ALL AS3 deployed configuration. 

_NOTE: Deploying to `/Common/Shared` tenant_

**Comment by mdditt2000** [comment]
@ghalevy have to tried to remove the tenant using the VSCODE extension

Connect to the BIG-IP via the extension, when you connect VSCODE will add the tenants under the AS3 section. Right click on the tenant to remove as shown below. 

![image](https://user-images.githubusercontent.com/12733938/166821492-b098e1ce-c50b-4efd-b23e-6f40cf3e0699.png)

Get more information about the VSCODE extension 

https://marketplace.visualstudio.com/items?itemName=F5DevCentral.vscode-f5

**Comment by megamattzilla** [comment]
It looks like an iRule dependency is causing the failure to delete:
```
{\"code\":422,\"message\":\"declaration failed\",\"response\":\"01070265:3: The rule (/Common/Shared/irule_library) cannot be deleted because it is in use by a rule (/Common/Shared/example_irule)
```

You can have an iRule call code from a shared iRule library using the call function: https://community.f5.com/t5/technical-articles/advanced-irules-getting-started-with-irules-procedures/ta-p/285783  

You cannot delete the library iRule before deleting the iRule that references it. It would be great to have a way to signal to AS3 an iRule that should be deleted last so that a TMOS exception does not occur.

**Comment by dstokesf5** [comment]
@ghalevy Do the above responses help you with your question?
