### ISSUE TITLE
AS3 doesn't deploy any tenant declarations if any one tenant declaration in invalid

### ISSUE THREAD

**Issue by arzzon** [F5Networks/f5-appsvcs-extension#702]
### Environment
 * Application Services Version: 3.41.0
 * BIG-IP Version: 15.0.1

### Summary
AS3 doesn't deploy any tenant declaration and responds with 422 if any one tenant declaration is invalid.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Submit declaration for two or more tenants in a single POST API call with all valid tenant declarations except one tenant 
   declaration which is invalid, having a BigIP reference that doesn't exist.
   For example a tenant declaration referencing a serverTLS that doesn't exist on bigIP( "serverTLS": "/Common/does-not-exist").
   https://x.x.x.x/mgmt/shared/appsvcs/declare/tenant1,tenant2

3. Observe the following error response:
AS3 responds with 422 code and none of the tenants declarations are deployed.

### Expected Behavior
Valid tenant declarations should be deployed, where as error should be thrown only for the invalid tenants.

### Actual Behavior
All the tenant declarations fail due to one invalid tenant declaration in the post call.

**Comment by mdditt2000** [comment]
@arzzon i think i have a good solution to resolve this issue. Since we going to be changing the mutex lock on the AS3 API to the tenant level it could be beneficial for CIS to POST directly to the tenant. This way it could be possible for for CIS to update multiple tenants at the same time. However not sure if CIS could do that. Lets chat
