### ISSUE TITLE
AS3 doesn't deploy any tenant declarations if any one tenant declaration is invalid

### ISSUE THREAD

**Issue by arzzon** [F5Networks/f5-appsvcs-extension#703]
### Environment
 * Application Services Version: 3.41.0
 * BIG-IP Version: 15.0.1

### Summary
AS3 doesn't deploy any tenant declaration and responds with 422 if any one tenant declaration is invalid.

### Steps To Reproduce
Steps to reproduce the behaviour:
1. Submit declaration for two or more tenants in a single POST API call with all valid tenant declarations except one tenant 
   declaration which is invalid, having a BigIP reference that doesn't exist.
   For example a tenant declaration referencing a serverTLS that doesn't exist on bigIP( "serverTLS": "/Common/does-not-exist").
   https://x.x.x.x/mgmt/shared/appsvcs/declare/tenant1,tenant2

3. Observe the following error response:
AS3 responds with 422 code and none of the tenants declarations are deployed.

### Expected Behavior
Valid tenant declarations should be deployed, where as error should be thrown only for the invalid tenants.

### Actual Behavior
All the tenant declarations fail due to one invalid tenant declaration in the post call.

**Comment by seattlevine** [comment]
Our [POST API documenttion](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/apidocs.html#tag/Configuration/paths/~1declare/post) indicates that code 422 means 'An invalid configuration was provided'. By design, this is not specific to a tenant. Deploying one tenant and not another from a declaration could easily lead to unexpected results. The error message should be specific enough to find the problem in the declaration.
If you need to deploy a single tenant from a declaration without breaking the declaration into pieces, you can post to a single tenant from a declaration. See [POSTing to a specific tenant](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/as3-api.html#posting-to-a-specific-tenant).

**Comment by mdditt2000** [comment]
Checking with AS3 development if the 422 error could display the tenant where the configuration is failing. CIS is sending a unified AS3 declaration for initial configuration. Updates are per tenant.
