### ISSUE TITLE
f5-appsvcs does not follow iControl LX extension life-cycle

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-appsvcs-extension#75]
##### Do you already have an issue opened with F5 support?
No

##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION
f5-appsvcs-3.9.0-3.noarch

##### BIGIP VERSION
TMOS 14.1

##### SUMMARY
The install task to install f5-appsvcs automatically installs f5-appsvcs-discovery, which is fine as long as an uninstall task issued for f5-appsvcs also uninstalls f5-appsvcs-discovery. Currently, an uninstall task on f5-appsvcs leaves f5-appsvcs-discovery extension installed. This will break automated extension management, and does not follow the iControl LX extension life-cycle as documented.

##### STEPS TO REPRODUCE
Install f5-appsvcs and then list the installed iControl LX extension. 

##### EXPECTED RESULTS
That install and uninstall tasks for the f5-appsvcs iControl LX extension would be symmetric.

##### ACTUAL RESULTS
f5-appsvcs-discovery is orphaned on TMOS devices.

**Comment by kaustriaf5** [comment]
Thanks @jgruber this is being tracked internally as 953.

**Comment by dstokesf5** [comment]
@jgruber Can you point out the documentation for the "iControl LX extension life-cycle"? I tried looking it up on Clouddocs, but I did not find anything.

**Comment by dstokesf5** [comment]
Unfortunately, this is not possible since the iControl LX Extension Framework offers no way to execute additional logic when a plugin is uninstalled. Closing this issue.

**Comment by jsevedge** [comment]
@dstokesf5 This still seems like a valid bug to address, regardless of technical difficulties right?  Perhaps to at least give the customer some options here what if installing service discovery was optional either 1) until it is needed or 2) user explicitly "enables" dependent extensions.  Another option to avoid changing that behavior might be to introduce support for a DELETE against one of the AS3 endpoints to indicate uninstall is imminent... something programmatic that client side code (like an SDK, created by F5 or otherwise could call to handle this scenario)

**Comment by dstokesf5** [comment]
We have decided that we are not interested in spending the resources required to fix this. Closing this issue.
